---

extends: "airbnb-base"

parserOptions:
  ecmaVersion: 6

env:
  browser: true
  jquery: true

rules:
  max-len:
    - error
    - 100
    - 2
    - ignoreComments: true

  comma-dangle:
    - error
    - never

  curly:
    - error
    - multi-line
    - consistent

  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true

  no-underscore-dangle:
    - error
    - allowAfterThis: true

  class-methods-use-this:
    - off

  no-mixed-operators:
    - error
    - allowSamePrecedence: true

  prefer-destructuring:
    - off

  no-case-declarations:
    - off

  no-param-reassign:
    - error
    - props: false

  arrow-body-style:
    - error
    - as-needed
    - requireReturnForObjectLiteral: true
